= Arquillian Drone image:https://travis-ci.org/arquillian/arquillian-extension-drone.svg["Build Status", link="https://travis-ci.org/arquillian/arquillian-extension-drone"]
:asciidoctor-source: https://raw.githubusercontent.com/arquillian/arquillian-extension-drone/master/docs
:numbered:
:sectlink:
:sectanchors:
:sectid:
:source-language: java
:source-highlighter: coderay
:sectnums:
:icons: font
:toc: left

ifndef::generated-doc[]
To read complete documentation visit http://arquillian.org/arquillian-extension-drone/
endif::generated-doc[]

The Arquillian Drone 2 extension for Arquillian provides a simple way
to include functional tests for an application with a web-based
user interface.

Arquillian Drone 2 brings the power of WebDriver into the Arquillian framework.
WebDriver serves as a language to communicate with the browser, by filling the forms, navigating the
pages and validating their content.

Compared with its predecessor Arquillian Drone 1, it offers
http://github.com/arquillian/arquillian-extension-drone/wiki/SPI-changes-in-Drone-2[new
features and tools] as part of the SPI as well as
http://github.com/arquillian/arquillian-extension-drone/wiki/API-changes-in-Drone-2[multiple
life cycle scopes of @Drone points] as part of the API.

== Why should I use Arquillian Drone instead of plain WebDriver?
There are many reasons why you want to do that, the most important being:

* Life cycle management of the browser
* Interaction with deployments and containers provided by Arquillian
* Simple usage of multiple browsers in a single test
* Configuration kept on a single place, outside of the Java code
* Fully compatible with the IDE
* Integration with mobile based browsers testing (https://github.com/arquillian/arquillian-droidium[Arquillian Droidium])
* Integration of JavaScript test suite execution (https://github.com/arquillian/arquillian-extension-qunit[Arquillian QUnit])
* Compatible with WebDriver (Selenium 2) and Selenium Grids

If you are still not convinced that Arquillian Drone matches your needs, you might have a look at https://github.com/arquillian/arquillian-graphene[Arquillian Graphene 2], which is a wrapper on top of WebDriver, goes one step further and provides you a convenient way how to write tests for rich AJAX UIs with an ease, injections for Page Objects and Page Fragments and much more.


ifdef::generated-doc[]

include::{asciidoctor-source}/drone-getting-started.adoc[]

include::{asciidoctor-source}/automatic-download.adoc[]

include::{asciidoctor-source}/supported-frameworks.adoc[]

include::{asciidoctor-source}/maven-setup.adoc[]

include::{asciidoctor-source}/life-cycle-scope-of-drone-points.adoc[]

include::{asciidoctor-source}/configuring-drone-instances.adoc[]

include::{asciidoctor-source}/drone-spi.adoc[]

endif::generated-doc[]

== Building the project

Prerequisites:

* JDK 8 and newer
* Maven 3.0.3 and newer

=== Running test suite

You can use Arquillian Spacelift to gather all the required binaries. Just run:

[source]
----
./gradlew test
----

This will run tests using multiple Arquillian Core versions and _phantomjs_ browser. In case you want to modify 
the behavior, you can specify +-ParquillianCoreVersions=1.1.12+ and +-Pbrowser=phantomjs,firefox+ for instance.
This will run integration test using a cross product of Arquillian Core and browsers defined.

WARNING: Running testsuite this way will modify all _pom.xml_ files in the project. Make sure you have committed all
your changes there first.

==== Manual way to run test suite

Prerequisites:

* running Selenium Server at port 4444, with paths to binaries required for remote browser execution. If you don't do it by yourself, Drone will run an instance of Selenium Server automatically. However in this case the server is started and stopped for each test class separately and only in a standalone mode with only one parameter `-port` that is taken from defined remoteAddress.
+
In case you want to specify other arguments to the selenium server, you can do so using the property,
+
`<property name="seleniumServerArgs">-debug -role hub -browserTimeout 1000</property>`
+
So, if you are fine with this automatic behavior you can skip this step, otherwise run your Selenium Server.

* installed web browsers you want to test
* you might want to align your layout to be the same as paths to binaries specified within arquillian.xml in _drone-webdriver_ module. Alternatively, you can override properties with 
 +-Darq.extension.${extensionQualifier}.${propertyName}+

Limitations:

* reusable sessions are not supported by Edge browser therefore related tests are skipped

In order to start Selenium Server, execute:

[source,bash]
java -Dphantomjs.binary.path=/path/to/phantomjs.binary -Dwebdriver.ie.driver=/path/to/iedriverserver.binary -jar selenium-server-standalone-3.5.1.jar

Once Selenium Server is running, you can run the tests by:

[source,bash]
mvn clean verify -Dbrowser=${browser}

Where browser has the same value as browser property from _arquillian.xml_ you want to tests (e.g. firefox, chrome, phantomjs, internetExplorer, opera, edge, chromeHeadless etc.)

TIP: VNC server instance can be used to let all the browsers pop out in separate display. Just prepend both commands with +DISPLAY=:${display.number}+

=== Releasing new version

Run following commands:

[source,bash]
mvn clean release:prepare release:perform

Make sure that you push the tag, close all issues with given version in JIRA and mark version as released.
