= Arquillian Drone BrowserStack WebDriver
This is an Arquillian extension that enables you to use the BrowserStack as a Drone WebDriver there in your functional tests.

=== How to use it:

1):: First of all, you need to have this extension on your project's classpath. Eg. as a maven dependency:
[source,xml]
----
    <dependency>
        <groupId>org.jboss.arquillian.extension</groupId>
        <artifactId>arquillian-drone-browserstack-webdriver</artifactId>
        <version>${version.org.jboss.arquillian.drone}</version>
    </dependency>
----

2):: To use the BrowserStackDriver you need to specify *browserstack* as a *browser* property:
[source,xml]
----
    <extension qualifier="webdriver">
        <property name="browser">browserstack</property>
        ...
    </extension>
----

3):: You can choose if you want to specify your credentials to access your account or to provide the URL directly with the credentials included.

::    a) To provide only the credentials you need to specify the *username* and *access.key* (in this case, the URL is created by the pattern: _http:// + username + : + automateKey + @hub.browserstack.com/wd/hub_)
[source,xml]
----
    <property name="username">*****</property>
    <property name="access.key">*****</property>
----

::    b) To provide the URL directly, please use the *url* parameter:
[source,xml]
----
    <property name="url">http://xxxx:zzzzz@hub.browserstack.com/wd/hub</property>
----

4):: Specify any property that you need to test you application with the BrowserStack there in your arquillian.xml. All the properties are passed to the WebDriver as the Capabilities. For example:
[source,xml]
----
    <extension qualifier="webdriver">
        <property name="browser">browserstack</property>

        <property name="username">*****</property>
        <property name="automate.key">*****</property>

        <property name="browserName">android</property>
        <property name="platform">ANDROID</property>
        <property name="device">Samsung Galaxy S5</property>
        <property name="browserstack.debug">true</property>
        ...
    </extension>
----

=== Local testing
To test against localhost and other locations behind your firewall, you need to run a BrowserStackLocal binary. For more information see these web pages
https://www.browserstack.com/local-testing
https://www.browserstack.com/automate/java#setting-local-tunnel.
As you can read there, there are two necessary things that have to be done to make local testing possible:

1) Run BrowserStackLocal with your access key

2) To have set the property *browserstack.local* to _true_ there in your arquillian.xml.

You can ask Drone for doing the first step instead of you. If you set another property *browserstack.local.managed* to _true_, Drone downloads and starts an appropriate binary before a webdriver is created. Command that is used for starting:

`./target/browserstacklocal/BrowserStackLocal -v <access_key>`

In case of using a named connection, then the starting command looks like this (where <connection> is taken from the property *browserstack.localIdentifier*):

`./target/browserstacklocal/BrowserStackLocal -v -localIdentifier <connection> <access_key>`
