version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  build:
    parameters:
      jdk-version:
        type: string
      browser:
        type: string
    working_directory: ~/circleci-arquillian
    docker:
      - image: cimg/openjdk:<< parameters.jdk-version >>-browsers
    steps:
      - run: cd /tmp
      - browser-tools/install-browser-tools:
          replace-existing-chrome: true
      - run:
          name: "Install Microsoft Edge for Linux"
          command: |
            ## Setup
            curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
            sudo install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/
            sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge-beta.list'
            sudo rm microsoft.gpg
            ## Install
            sudo apt update
            sudo apt install microsoft-edge-beta -y
      - checkout
      - restore_cache:
          key: circleci-arquillian-extension-drone-{{ checksum "pom.xml" }}
      - run: ./mvnw verify -q -U -DskipTests
      - run: 
          name: "Run tests"
          command: ./mvnw verify -Dbrowser=<< parameters.browser >>
          environment:
            OPENSSL_CONF: /dev/null
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-arquillian-extension-drone-{{ checksum "pom.xml" }}

workflows:
  version: 2.1
  circleci_build:
    jobs:
      - build:
          name: build-jdk-<< matrix.jdk-version >>-<< matrix.browser >>
          matrix:
            parameters:
              jdk-version: ["8.0"]
              browser: ["chromeHeadless", "htmlunit", "firefox", "edge" ]

