ifdef::env-github,env-browser[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:outfilesuffix: .adoc
endif::[]

== Automatic Download
Drone provides a functionality of automatic download of some binaries such as browser webdriver and Selenium Server jar. Which binaries and which features are supported can be found in tables below.

=== How it works?

Let say that I want to use Chrome for my UI tests. First of all, Drone checks if the path to the webdriver binary isn't already set. In this case it would check a system property `webdriver.chrome.driver`; if this is empty then it checks arquillian.xml property: `chromeDriverBinary`. In case that both properties are empty, then the automatic download comes up.

Now we have several options how to specify which binary should be downloaded and where it should be stored. For storage purposes cache directories `$HOME/.arquillian/drone/subdirectory_specific_to_binary` are used so the binaries are not downloaded over and over again.

==== Version
Using the property

`<property name="chromeDriverVersion">2.10</property>`

you can define which version of the Chrome webdriver should be downloaded. The binary is then cached in a directory `$HOME/.arquillian/drone/chrome/2.10/`.

==== URL
Using the property

`<property name="chromeDriverUrl">http://url/to/chrome/webdriver </property>`

you can define which url the Chrome webdriver should be downloaded from. The directory where it is stored depends if you also specify the version of this binary or not. In case you use also the before-mentioned property `chromeDriverVersion` then it is cached in corresponding directory `$HOME/.arquillian/drone/chrome/specified_version/`; otherwise it is downloaded into `$project.directory/target/drone/downloaded/` so no cache is used.

==== Latest
In case that you don't define any property then Drone finds the latest version of the given binary and downloads this one. The binary (in case of Chrome webdriver) is cached at `$HOME/.arquillian/drone/chrome/latest_version/`.


==== Properties, directory names and support of latest versions

Explanatory notes:

_System property_ - intended to be used as a system property to define a path to a binary

_arquillian.xml property_ - intended to be used as a property used in arquillian.xml file to define a path to a binary

_Resolution of latest version supported_ - if the latest version is resolved when no property is defined

_Version driver property_ - use this arquillian.xml property to define version of the binary that should be downloaded/used

_Url driver property_ - use this arquillian.xml property to define an URL the binary should be downloaded from

_Cache subdirectory_ - name of the sub-directory (withing `$HOME/.arquillian/drone/`) the binaries are cached in

_Architecture_ - in arquillian.xml file, you can explicitly specify the target architecture of the binary for selected webdrivers; if not specified it's then resolved from the host OS

===== Selenium Server
|===

|System property |selenium.server.binary.path

|arquillian.xml property
|seleniumServerBinary

|Resolution of latest version supported
|yes

|Version driver property
|seleniumServerVersion

|Url driver property
|seleniumServerUrl

|Cache subdirectory
|selenium-server
|===

===== Gecko driver (Firefox)
|===

|System property |webdriver.gecko.driver

|arquillian.xml property
|firefoxDriverBinary

|Resolution of latest version supported
|yes

|Version driver property
|firefoxDriverVersion

|Url driver property
|firefoxDriverUrl

|Cache subdirectory
|firefox
|===


===== Chrome driver
|===

|System property |webdriver.chrome.driver

|arquillian.xml property
|chromeDriverBinary

|Resolution of latest version supported
|yes

|Version driver property
|chromeDriverVersion

|Url driver property
|chromeDriverUrl

|Cache subdirectory
|chrome
|===


===== Edge driver
|===

|System property |webdriver.edge.driver

|arquillian.xml property
|edgeDriverBinary

|Resolution of latest version supported
|yes

|Version driver property
|edgeDriverVersion

|Url driver property
|edgeDriverUrl

|Cache subdirectory
|edge
|===


===== IE driver
|===

|System property |webdriver.ie.driver

|arquillian.xml property
|ieDriverBinary

|Resolution of latest version supported
|yes

|Version driver property
|ieDriverVersion

|Url driver property
|ieDriverUrl

|Cache subdirectory
|internetExplorer

|Architecture
|ieDriverArch +
Supported values: "Win32" and "x64"
|===

The architecture of the binary can be explicitly specified because the 64 bit version of the IE driver is having issues with `sendKeys` method at some specific conditions.

===== Opera driver
|===

|System property |webdriver.opera.driver

|arquillian.xml property
|operaDriverBinary

|Resolution of latest version supported
|no

|Version driver property
|operaDriverVersion (only in combination with url)

|Url driver property
|operaDriverUrl

|Cache subdirectory
|opera
|===


===== Safari driver
|===

|System property |-

|arquillian.xml property
|-

|Resolution of latest version supported
|no

|Version driver property
|-

|Url driver property
|no

|Cache subdirectory
|-
|===


[NOTE]
====
*We are not supporting `Automatic downloading for safari` & `Download webdriver from a specific URL`
due to following reasons:*

* *Automatic Downloading for Safari:* +
Starting with Safari 10 on OS X El Capitan and macOS Sierra, Safari comes bundled with a new driver
implementation that’s maintained by the Web Developer Experience team at Apple.
Safari’s driver is launchable via the /usr/bin/safaridriver executable, and most client libraries
provided by Selenium will automatically launch the driver this way without further configuration.
https://webkit.org/blog/6900/webdriver-support-in-safari-10/[Safari-10]
* *Download Webdriver from a specific URL:* +
Starting with Selenium 2.48.0, you must manually install the SafariDriver browser extension.
Refer getting started section from https://github.com/SeleniumHQ/selenium/wiki/SafariDriver[SafariDiver]
====

==== GitHub rate limit

In case of downloading webdrivers from GitHub, you may reach rate limit for unauthenticated requests (60 per hour). To avoid this, there has been implemented GitHub release caching functionality that caches GitHub responses based on the last modification date from the returned response header.

===== Authenticated requests

In some cases (larger CI matrix jobs) this response caching doesn't have to suffice. To use authenticated requests (where the rate limit is much higher) you need to specify your GitHub username and secret token in your arquillian.xml file:

[source,xml]
----
<property name="githubUsername">username</property>
<property name="githubToken">secretToken</property>
----

=== Activate / Deactivate

The automatic download functionality is activated by default; if you want to set it off use the property:

`<property name="downloadBinaries">false</property>`

and no binary will be downloaded.


=== Selenium Server

Apart from the fact that the Selenium Server binary is automatically downloaded, in the case of @RemoteWebDriver@ it is also automatically started with the correct parameters (path to the webdriver that should be used).

So, if you use `RemoteWebDriver` Drone checks the address specified using property `remoteAddress` in arquillian.xml file (default is: `http://localhost:4444/wd/hub`) and if the address is not accessible (there isn't running anything) then it automatically starts selenium server instance on the given address.

For example I'd like to use `RemoteWebDriver` with the browser Firefox and without specifying any custom remote address, then the Selenium Server would be started using command:

`java -Dwebdriver.gecko.driver=target/.../geckodriver -jar target/.../selenium-server-standalone-3.11.0.jar -port 4444`

In case you would like to add some additional selenium server arguments to the command, you can use parameter `seleniumServerArgs` in your arquillian.xml file.
For example, if you used these properties:

[source,xml]
----
<property name="seleniumServerArgs">-debug true -role node -browserTimeout 1000</property>
<property name="browser">firefox</property>
----

then the command used for starting Selenium Server instance would look like:

`java -Dwebdriver.gecko.driver=target/.../geckodriver -jar target/.../selenium-server-standalone-3.11.0.jar -port 4444 -debug true -role node -browserTimeout 1000`

